build:
    stage: build
    tags:
    - windows
    script:
    - git submodule update --init --recursive
    - choco install autohotkey.install --params='/DefaultVer:A32'
    - ./COMPILE.bat
    artifacts:
        paths:
        - loader.exe

